### PR TITLE
[CI] Enable option to automatically resolve clang-tidy comments

### PR DESCRIPTION
**Pull request by psalz**
Let's give this feature a try!

### CODE REVIEW

**Comment by fknorr** [comment]
Do we want to test this on some dummy changes?

**Comment by psalz** [comment]
I'll temporarily include it in #300 to see if it works!

**Comment by psalz** [comment]
Since including this in #300 didn't really do anything I checked the source and it [looks like](https://github.com/platisd/clang-tidy-pr-comments/blob/88780c4ca5471b97de8f228219d1e39b1a472142/run_action.py#L750) unfortunately this feature is not as smart as a thought: It simply closes all comments once there are no warnings being generated.

**Comment by psalz** [comment]
Closing since we expect fewer warnings going foward because of #311.

**Pull request closed without merging**
